/*
 * generated by Xtext 2.23.0
 */
package idm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import idm.QsvRuntimeModule;
import idm.QsvStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class QsvIdeSetup extends QsvStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new QsvRuntimeModule(), new QsvIdeModule()));
	}
	
}
