/*
 * generated by Xtext 2.23.0
 */
package idm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class QsvUiModule extends AbstractQsvUiModule {

	public QsvUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
