/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalQsvParser;
import org.xtext.example.mydsl.services.QsvGrammarAccess;

public class QsvParser extends AbstractAntlrParser {

	@Inject
	private QsvGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQsvParser createParser(XtextTokenStream stream) {
		return new InternalQsvParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public QsvGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QsvGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
