FROM gradle:jdk11

COPY . .

RUN ln -s /usr/bin/python3 /usr/local/bin/python
RUN apt-get -y update && apt-get install -y python3-pip
RUN pip3 install pandas==1.1.4

RUN gradle test

RUN gradle shadowJar

ENTRYPOINT ["./run-generator.sh"]


