FROM gradle:jdk11

RUN apt-get -y update
RUN apt-get install bsdmainutils -y  
RUN ln -s /usr/bin/python3 /usr/local/bin/python
RUN apt-get install -y python3-pip -y
RUN pip3 install pandas==1.1.4

COPY . .

RUN python3 qsv-code/generate.py
CMD "python3" "benchmark.py"

