/*
 * generated by Xtext 2.23.0
 */
package idm.ui.tests;

import com.google.inject.Injector;
import idm.qsv.ui.internal.QsvActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class QsvUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return QsvActivator.getInstance().getInjector("idm.Qsv");
	}

}
