/**
 * generated by Xtext 2.23.0
 */
package idm.qsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link idm.qsv.Boolean#getBol <em>Bol</em>}</li>
 * </ul>
 *
 * @see idm.qsv.QsvPackage#getBoolean()
 * @model
 * @generated
 */
public interface Boolean extends Value
{
  /**
   * Returns the value of the '<em><b>Bol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bol</em>' attribute.
   * @see #setBol(String)
   * @see idm.qsv.QsvPackage#getBoolean_Bol()
   * @model
   * @generated
   */
  String getBol();

  /**
   * Sets the value of the '{@link idm.qsv.Boolean#getBol <em>Bol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bol</em>' attribute.
   * @see #getBol()
   * @generated
   */
  void setBol(String value);

} // Boolean
