/**
 * generated by Xtext 2.23.0
 */
package idm.qsv;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Col Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link idm.qsv.ColRange#getStart <em>Start</em>}</li>
 *   <li>{@link idm.qsv.ColRange#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see idm.qsv.QsvPackage#getColRange()
 * @model
 * @generated
 */
public interface ColRange extends EObject
{
  /**
   * Returns the value of the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' containment reference.
   * @see #setStart(Column)
   * @see idm.qsv.QsvPackage#getColRange_Start()
   * @model containment="true"
   * @generated
   */
  Column getStart();

  /**
   * Sets the value of the '{@link idm.qsv.ColRange#getStart <em>Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' containment reference.
   * @see #getStart()
   * @generated
   */
  void setStart(Column value);

  /**
   * Returns the value of the '<em><b>End</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' containment reference.
   * @see #setEnd(Column)
   * @see idm.qsv.QsvPackage#getColRange_End()
   * @model containment="true"
   * @generated
   */
  Column getEnd();

  /**
   * Sets the value of the '{@link idm.qsv.ColRange#getEnd <em>End</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' containment reference.
   * @see #getEnd()
   * @generated
   */
  void setEnd(Column value);

} // ColRange
