/**
 * generated by Xtext 2.23.0
 */
package idm.qsv;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see idm.qsv.QsvPackage#getColumn()
 * @model
 * @generated
 */
public interface Column extends EObject
{
} // Column
