/**
 * generated by Xtext 2.23.0
 */
package idm.qsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link idm.qsv.ColumnName#getNameb <em>Nameb</em>}</li>
 * </ul>
 *
 * @see idm.qsv.QsvPackage#getColumnName()
 * @model
 * @generated
 */
public interface ColumnName extends Column
{
  /**
   * Returns the value of the '<em><b>Nameb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nameb</em>' attribute.
   * @see #setNameb(String)
   * @see idm.qsv.QsvPackage#getColumnName_Nameb()
   * @model
   * @generated
   */
  String getNameb();

  /**
   * Sets the value of the '{@link idm.qsv.ColumnName#getNameb <em>Nameb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nameb</em>' attribute.
   * @see #getNameb()
   * @generated
   */
  void setNameb(String value);

} // ColumnName
