/**
 * generated by Xtext 2.23.0
 */
package idm.qsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Column Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link idm.qsv.ColumnNumber#getNumber <em>Number</em>}</li>
 * </ul>
 *
 * @see idm.qsv.QsvPackage#getColumnNumber()
 * @model
 * @generated
 */
public interface ColumnNumber extends Column
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see idm.qsv.QsvPackage#getColumnNumber_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link idm.qsv.ColumnNumber#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

} // ColumnNumber
