/**
 * generated by Xtext 2.23.0
 */
package idm.qsv;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Header</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link idm.qsv.Header#getNameFile <em>Name File</em>}</li>
 *   <li>{@link idm.qsv.Header#isHasColumnName <em>Has Column Name</em>}</li>
 * </ul>
 *
 * @see idm.qsv.QsvPackage#getHeader()
 * @model
 * @generated
 */
public interface Header extends EObject
{
  /**
   * Returns the value of the '<em><b>Name File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name File</em>' attribute.
   * @see #setNameFile(String)
   * @see idm.qsv.QsvPackage#getHeader_NameFile()
   * @model
   * @generated
   */
  String getNameFile();

  /**
   * Sets the value of the '{@link idm.qsv.Header#getNameFile <em>Name File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name File</em>' attribute.
   * @see #getNameFile()
   * @generated
   */
  void setNameFile(String value);

  /**
   * Returns the value of the '<em><b>Has Column Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Has Column Name</em>' attribute.
   * @see #setHasColumnName(boolean)
   * @see idm.qsv.QsvPackage#getHeader_HasColumnName()
   * @model
   * @generated
   */
  boolean isHasColumnName();

  /**
   * Sets the value of the '{@link idm.qsv.Header#isHasColumnName <em>Has Column Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Has Column Name</em>' attribute.
   * @see #isHasColumnName()
   * @generated
   */
  void setHasColumnName(boolean value);

} // Header
