/**
 * generated by Xtext 2.23.0
 */
package idm.qsv;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Highest Priority</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link idm.qsv.HighestPriority#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see idm.qsv.QsvPackage#getHighestPriority()
 * @model
 * @generated
 */
public interface HighestPriority extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(EObject)
   * @see idm.qsv.QsvPackage#getHighestPriority_Condition()
   * @model containment="true"
   * @generated
   */
  EObject getCondition();

  /**
   * Sets the value of the '{@link idm.qsv.HighestPriority#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(EObject value);

} // HighestPriority
