/**
 * generated by Xtext 2.23.0
 */
package idm.qsv;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mid Priority</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link idm.qsv.MidPriority#getHigh <em>High</em>}</li>
 *   <li>{@link idm.qsv.MidPriority#getAndCondition <em>And Condition</em>}</li>
 * </ul>
 *
 * @see idm.qsv.QsvPackage#getMidPriority()
 * @model
 * @generated
 */
public interface MidPriority extends EObject
{
  /**
   * Returns the value of the '<em><b>High</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>High</em>' containment reference.
   * @see #setHigh(HighestPriority)
   * @see idm.qsv.QsvPackage#getMidPriority_High()
   * @model containment="true"
   * @generated
   */
  HighestPriority getHigh();

  /**
   * Sets the value of the '{@link idm.qsv.MidPriority#getHigh <em>High</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>High</em>' containment reference.
   * @see #getHigh()
   * @generated
   */
  void setHigh(HighestPriority value);

  /**
   * Returns the value of the '<em><b>And Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>And Condition</em>' containment reference.
   * @see #setAndCondition(MidPriority)
   * @see idm.qsv.QsvPackage#getMidPriority_AndCondition()
   * @model containment="true"
   * @generated
   */
  MidPriority getAndCondition();

  /**
   * Sets the value of the '{@link idm.qsv.MidPriority#getAndCondition <em>And Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>And Condition</em>' containment reference.
   * @see #getAndCondition()
   * @generated
   */
  void setAndCondition(MidPriority value);

} // MidPriority
