/**
 * generated by Xtext 2.23.0
 */
package idm.qsv;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link idm.qsv.Print#getPrint <em>Print</em>}</li>
 * </ul>
 *
 * @see idm.qsv.QsvPackage#getPrint()
 * @model
 * @generated
 */
public interface Print extends EObject
{
  /**
   * Returns the value of the '<em><b>Print</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Print</em>' attribute.
   * @see #setPrint(String)
   * @see idm.qsv.QsvPackage#getPrint_Print()
   * @model
   * @generated
   */
  String getPrint();

  /**
   * Sets the value of the '{@link idm.qsv.Print#getPrint <em>Print</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Print</em>' attribute.
   * @see #getPrint()
   * @generated
   */
  void setPrint(String value);

} // Print
