/**
 * generated by Xtext 2.23.0
 */
package idm.qsv;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see idm.qsv.QsvFactory
 * @model kind="package"
 * @generated
 */
public interface QsvPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "qsv";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Qsv.idm";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "qsv";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QsvPackage eINSTANCE = idm.qsv.impl.QsvPackageImpl.init();

  /**
   * The meta object id for the '{@link idm.qsv.impl.QuerySepartedValueImpl <em>Query Separted Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see idm.qsv.impl.QuerySepartedValueImpl
   * @see idm.qsv.impl.QsvPackageImpl#getQuerySepartedValue()
   * @generated
   */
  int QUERY_SEPARTED_VALUE = 0;

  /**
   * The feature id for the '<em><b>Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_SEPARTED_VALUE__HEADER = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_SEPARTED_VALUE__STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Query Separted Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_SEPARTED_VALUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link idm.qsv.impl.HeaderImpl <em>Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see idm.qsv.impl.HeaderImpl
   * @see idm.qsv.impl.QsvPackageImpl#getHeader()
   * @generated
   */
  int HEADER = 1;

  /**
   * The feature id for the '<em><b>Name File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__NAME_FILE = 0;

  /**
   * The feature id for the '<em><b>Has Column Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__HAS_COLUMN_NAME = 1;

  /**
   * The number of structural features of the '<em>Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link idm.qsv.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see idm.qsv.impl.StatementImpl
   * @see idm.qsv.impl.QsvPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__STATEMENT = 0;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link idm.qsv.impl.PrintImpl <em>Print</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see idm.qsv.impl.PrintImpl
   * @see idm.qsv.impl.QsvPackageImpl#getPrint()
   * @generated
   */
  int PRINT = 3;

  /**
   * The feature id for the '<em><b>Print</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT__PRINT = 0;

  /**
   * The number of structural features of the '<em>Print</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link idm.qsv.QuerySepartedValue <em>Query Separted Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query Separted Value</em>'.
   * @see idm.qsv.QuerySepartedValue
   * @generated
   */
  EClass getQuerySepartedValue();

  /**
   * Returns the meta object for the containment reference '{@link idm.qsv.QuerySepartedValue#getHeader <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Header</em>'.
   * @see idm.qsv.QuerySepartedValue#getHeader()
   * @see #getQuerySepartedValue()
   * @generated
   */
  EReference getQuerySepartedValue_Header();

  /**
   * Returns the meta object for the containment reference list '{@link idm.qsv.QuerySepartedValue#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see idm.qsv.QuerySepartedValue#getStatements()
   * @see #getQuerySepartedValue()
   * @generated
   */
  EReference getQuerySepartedValue_Statements();

  /**
   * Returns the meta object for class '{@link idm.qsv.Header <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Header</em>'.
   * @see idm.qsv.Header
   * @generated
   */
  EClass getHeader();

  /**
   * Returns the meta object for the attribute '{@link idm.qsv.Header#getNameFile <em>Name File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name File</em>'.
   * @see idm.qsv.Header#getNameFile()
   * @see #getHeader()
   * @generated
   */
  EAttribute getHeader_NameFile();

  /**
   * Returns the meta object for the attribute '{@link idm.qsv.Header#isHasColumnName <em>Has Column Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Has Column Name</em>'.
   * @see idm.qsv.Header#isHasColumnName()
   * @see #getHeader()
   * @generated
   */
  EAttribute getHeader_HasColumnName();

  /**
   * Returns the meta object for class '{@link idm.qsv.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see idm.qsv.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the containment reference '{@link idm.qsv.Statement#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Statement</em>'.
   * @see idm.qsv.Statement#getStatement()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Statement();

  /**
   * Returns the meta object for class '{@link idm.qsv.Print <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print</em>'.
   * @see idm.qsv.Print
   * @generated
   */
  EClass getPrint();

  /**
   * Returns the meta object for the attribute '{@link idm.qsv.Print#getPrint <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Print</em>'.
   * @see idm.qsv.Print#getPrint()
   * @see #getPrint()
   * @generated
   */
  EAttribute getPrint_Print();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  QsvFactory getQsvFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link idm.qsv.impl.QuerySepartedValueImpl <em>Query Separted Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see idm.qsv.impl.QuerySepartedValueImpl
     * @see idm.qsv.impl.QsvPackageImpl#getQuerySepartedValue()
     * @generated
     */
    EClass QUERY_SEPARTED_VALUE = eINSTANCE.getQuerySepartedValue();

    /**
     * The meta object literal for the '<em><b>Header</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY_SEPARTED_VALUE__HEADER = eINSTANCE.getQuerySepartedValue_Header();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY_SEPARTED_VALUE__STATEMENTS = eINSTANCE.getQuerySepartedValue_Statements();

    /**
     * The meta object literal for the '{@link idm.qsv.impl.HeaderImpl <em>Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see idm.qsv.impl.HeaderImpl
     * @see idm.qsv.impl.QsvPackageImpl#getHeader()
     * @generated
     */
    EClass HEADER = eINSTANCE.getHeader();

    /**
     * The meta object literal for the '<em><b>Name File</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEADER__NAME_FILE = eINSTANCE.getHeader_NameFile();

    /**
     * The meta object literal for the '<em><b>Has Column Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEADER__HAS_COLUMN_NAME = eINSTANCE.getHeader_HasColumnName();

    /**
     * The meta object literal for the '{@link idm.qsv.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see idm.qsv.impl.StatementImpl
     * @see idm.qsv.impl.QsvPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__STATEMENT = eINSTANCE.getStatement_Statement();

    /**
     * The meta object literal for the '{@link idm.qsv.impl.PrintImpl <em>Print</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see idm.qsv.impl.PrintImpl
     * @see idm.qsv.impl.QsvPackageImpl#getPrint()
     * @generated
     */
    EClass PRINT = eINSTANCE.getPrint();

    /**
     * The meta object literal for the '<em><b>Print</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRINT__PRINT = eINSTANCE.getPrint_Print();

  }

} //QsvPackage
