/**
 * generated by Xtext 2.23.0
 */
package idm.qsv;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query Separated Values</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link idm.qsv.QuerySeparatedValues#getHeader <em>Header</em>}</li>
 *   <li>{@link idm.qsv.QuerySeparatedValues#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see idm.qsv.QsvPackage#getQuerySeparatedValues()
 * @model
 * @generated
 */
public interface QuerySeparatedValues extends EObject
{
  /**
   * Returns the value of the '<em><b>Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Header</em>' containment reference.
   * @see #setHeader(Header)
   * @see idm.qsv.QsvPackage#getQuerySeparatedValues_Header()
   * @model containment="true"
   * @generated
   */
  Header getHeader();

  /**
   * Sets the value of the '{@link idm.qsv.QuerySeparatedValues#getHeader <em>Header</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Header</em>' containment reference.
   * @see #getHeader()
   * @generated
   */
  void setHeader(Header value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link idm.qsv.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see idm.qsv.QsvPackage#getQuerySeparatedValues_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // QuerySeparatedValues
