/**
 * generated by Xtext 2.23.0
 */
package idm.qsv.impl;

import idm.qsv.ColumnName;
import idm.qsv.QsvPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Column Name</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link idm.qsv.impl.ColumnNameImpl#getNameb <em>Nameb</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ColumnNameImpl extends ColumnImpl implements ColumnName
{
  /**
   * The default value of the '{@link #getNameb() <em>Nameb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameb()
   * @generated
   * @ordered
   */
  protected static final String NAMEB_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNameb() <em>Nameb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameb()
   * @generated
   * @ordered
   */
  protected String nameb = NAMEB_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ColumnNameImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return QsvPackage.Literals.COLUMN_NAME;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNameb()
  {
    return nameb;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNameb(String newNameb)
  {
    String oldNameb = nameb;
    nameb = newNameb;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, QsvPackage.COLUMN_NAME__NAMEB, oldNameb, nameb));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case QsvPackage.COLUMN_NAME__NAMEB:
        return getNameb();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case QsvPackage.COLUMN_NAME__NAMEB:
        setNameb((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case QsvPackage.COLUMN_NAME__NAMEB:
        setNameb(NAMEB_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case QsvPackage.COLUMN_NAME__NAMEB:
        return NAMEB_EDEFAULT == null ? nameb != null : !NAMEB_EDEFAULT.equals(nameb);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nameb: ");
    result.append(nameb);
    result.append(')');
    return result.toString();
  }

} //ColumnNameImpl
