/*
 * generated by Xtext 2.23.0
 */
package idm.validation;

import org.eclipse.xtext.validation.ComposedChecks;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
// Changing this file to .xtend results in a default .java
// validator to be created when generating the grammar
// So we reference the other validation class here instead
@ComposedChecks(validators={QsvChecksValidator.class})
public class QsvValidator extends AbstractQsvValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					QsvPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
